### ISSUE TITLE
မှတ်ချက်ထည့်၍ မရ

### ISSUE THREAD

**Issue by akhin57** [eimg/mediumy#1]
မှတ်ချက်ထည့်လျှင် နှလုံး အရေအတွက်တိုးပြီး၊  မှတ်ချက် အရေအတွက်တွင် NaN ပြပါသည်။  comment လည်း မဝင်ပါ။

**Comment by eimg** [comment]
The comment issue fixed. Please re-open if you find it still unresolved.
