### ISSUE TITLE
Post UI suggestion

### ISSUE THREAD

**Issue by mrlinnth** [eimg/mediumy#6]
It would be really great if the article and page background has slightly different color.

And the space on top after user avatar and name seems wasted. How about showing the user on the left of the Title text?

Attached a sample.

![2017-08-17-13_36_35-mediumy---](https://user-images.githubusercontent.com/4952597/29400220-785bebb8-8352-11e7-8503-4766908ff391.jpg)

**Comment by eimg** [comment]
Thanks for the suggestion but it's the design decision inspired by original Medium.
